In [7]:
import numpy as np
import pandas as pd

import datetime
from niftyutils import load_nifty_data

In [9]:
DATA_DIR = './../data/'

In [28]:
start_date = datetime.datetime(2010,9,30)
end_date = datetime.datetime(2020,9,30)
nifty_data = load_nifty_data(start_date,end_date)

In [29]:
nifty_data['pct_change'] = (nifty_data['Close']/nifty_data['Close'].shift(1) - 1)*100
nifty_data = nifty_data.dropna()
nifty_data

                Open      High       Low     Close       Volume  pct_change
Date
2010-10-01   6030.30   6153.10   6030.30   6143.40  179170000.0    1.881442
2010-10-04   6144.70   6222.10   6144.70   6159.45  184600000.0    0.261256
2010-10-05   6159.45   6188.35   6118.05   6145.80  145240000.0   -0.221611
2010-10-06   6150.95   6223.40   6148.60   6186.45  152500000.0    0.661427
2010-10-07   6186.85   6199.45   6107.50   6120.30  168880000.0   -1.069272
...              ...       ...       ...       ...          ...         ...
2020-09-24  11011.00  11015.30  10790.20  10805.55  706139506.0   -2.931229
2020-09-25  10910.40  11072.60  10854.85  11050.25  559597322.0    2.264577
2020-09-28  11140.85  11239.35  11099.85  11227.55  472777324.0    1.604489
2020-09-29  11288.60  11305.40  11181.00  11222.40  498295735.0   -0.045869
2020-09-30  11244.45  11295.40  11184.55  11247.55  499343849.0    0.224105

[2476 rows x 6 columns]

In [30]:
vix_data = pd.read_csv(DATA_DIR+'vix_data.csv',index_col=['Date '],parse_dates=True)

In [35]:
nifty_vix_data = pd.concat([nifty_data['pct_change'].rename('nifty change'),vix_data['% Change'].rename('vix change')], axis=1, join = 'inner')

In [39]:
nifty_vix_data[(nifty_vix_data['nifty change'] > 0.0) & (nifty_vix_data['vix change'] > 5)]

            nifty change  vix change
2010-10-04      0.261256        6.39
2011-07-25      0.822691        7.20
2011-12-07      0.465356        5.76
2012-02-21      0.770088        8.56
2012-09-17      0.579993       15.60
2012-10-29      0.022951        6.40
2012-11-05      0.114081        7.10
2012-11-29      1.703201       10.10
2013-02-18      0.183443        6.89
2013-04-22      0.887067        5.60
2013-04-30      0.442066        5.37
2013-05-02      1.166065        7.81
2013-05-15      2.524435        5.59
2013-11-25      1.999850        5.04
2013-12-02      0.675993        9.26
2014-03-07      1.960585       15.51
2014-03-10      0.162411        6.32
2014-03-31      0.123956       16.06
2014-04-07      0.010457        9.98
2014-04-09      1.510818        7.85
2014-04-10      0.002943        6.71
2014-04-21      0.564209       11.45
2014-05-09      2.987305        9.93
2014-05-15      0.202567       13.40
2014-06-09      0.938893        6.96
2014-07-07      0.458615        6.90
2014-11-11      0.220511        6.25
2015-01-16      0.231336        6.90
2015-01-28      0.042646        9.32
2015-04-06      0.857767        6.64
2015-08-03      0.119538        5.63
2015-08-28      0.666755        5.84
2016-04-18      0.818424        5.69
2017-01-27      0.447531        5.50
2017-04-26      0.486214        5.24
2017-05-02      0.104793        5.41
2017-05-29      0.102135        8.52
2017-07-31      0.625094        6.85
2017-10-30      0.393295        5.56
2018-01-22      0.656282       10.08
2018-01-23      1.071474        5.41
2018-01-24      0.020751       11.19
2018-11-26      0.967535        6.48
2019-01-21      0.503349        9.21
2019-03-18      0.309359        6.52
2019-05-22      0.245963        7.72
2019-09-23      2.891558        9.04
2019-10-29      1.752001        5.36
2019-12-09      0.134211        7.02
2020-03-13      3.806510       25.05
2020-03-24      2.507145       16.15